version: "3.9"

services:
  frontend:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    volumes:
      - ./nextjs:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    container_name: nirvana
    command: npm run dev
    environment:
      - WATCHPACK_POLLING=true
    # environment:
    #   - NODE_ENV=development
